apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml
  - backend.yaml
  - frontend.yaml

configMapGenerator:
  - name: nginx-conf
    files:
      - default.conf=nginx.conf
  - name: cassandra-config
    literals:
      - CASSANDRA_HOSTS=10.0.0.10,10.0.1.10,10.0.2.10

secretGenerator:
  - name: backend-secrets
    files:
      - jwt-secret=jwt-secret.txt
      - CASSANDRA_USERNAME=secrets/cassandra-app-username.txt
      - CASSANDRA_PASSWORD=secrets/cassandra-app-password.txt

images:
  - name: backend
    newName: 935803162478.dkr.ecr.ca-central-1.amazonaws.com/mychatapp/backend
    newTag: v1.4
  - name: frontend
    newName: 935803162478.dkr.ecr.ca-central-1.amazonaws.com/mychatapp/frontend
    newTag: v1.4