apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storageclass.yaml
  - cassandra.yaml
  - cassandra-init-job.yaml
  - redis.yaml
  - backend.yaml
  - frontend.yaml

# for things that should be shared, gitignored, or need hash-triggered rollouts
# kustomize hashes the ConfigMap name and rewrites the reference, so changing a value causes a pod rollout
configMapGenerator:
  # init.cql mounted into the cassandra-init Job
  - name: cassandra-schema
    files:
      - init.cql
  # nginx.conf mounted over /etc/nginx/conf.d/default.conf in the frontend
  - name: nginx-conf
    files:
      - default.conf=nginx.conf

secretGenerator:
  # jwt-secret.txt in .gitignore.
  - name: backend-secrets
    files:
      - jwt-secret=jwt-secret.txt

images:
  - name: backend
    newName: 935803162478.dkr.ecr.ca-central-1.amazonaws.com/mychatapp/backend
    newTag: v1.3
  - name: frontend
    newName: 935803162478.dkr.ecr.ca-central-1.amazonaws.com/mychatapp/frontend
    newTag: v1.3