apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer  # the scheduler places the pod first, then the volume is provisioned in whatever AZ the pod landed in.
allowVolumeExpansion: true
reclaimPolicy: Delete